when@dev: &aws_dev
  async_aws:
    config:
      region: eu-west-2

    clients:
      s3:
        config:
          endpoint: 'http://localstack:4566'
          pathStyleEndpoint: true

when@test: *aws_dev

when@prod:
  async_aws: