name: Release Drafter

on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, reopened, labeled, unlabeled, synchronize]

permissions:
    contents: read

jobs:
    # Prepare the release _before_ validating the labels, as Release Drafter will
    # automatically tag the PR with the appropriate labels based on branch names.
    update_release:
        name: Prepare Release
        permissions:
            # Allow access to create Releases
            contents: write
            # Allow access to auto-labelling PRs (for categorisation)
            pull-requests: write
        runs-on: ubuntu-latest

        steps:
            - uses: release-drafter/release-drafter@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    check_labels:
        name: Validate Labels
        runs-on: ubuntu-latest
        needs: update_release

        steps:
            - name: Check for categorisation labels
              uses: danielchabr/pr-labels-checker@v3.3
              with:
                  hasSome: feature,bug,chore
                  githubToken: ${{ secrets.GITHUB_TOKEN }}

            - name: Check for Semver labels
              uses: danielchabr/pr-labels-checker@v3.3
              with:
                  hasSome: bump-major,bump-minor,bump-patch
                  githubToken: ${{ secrets.GITHUB_TOKEN }}